### ISSUE TITLE
Define materials problem

### ISSUE THREAD

**Issue by bgpantojar** [NumSoftware/Amaru#16]
When is used label identification to define materials of elements, it presents a problem when the function domain(mesh,materials) is used. 
![captura de tela de 2018-06-25 13-09-52](https://user-images.githubusercontent.com/35929939/41868002-565f9596-787a-11e8-9bb4-cadd04432dc4.png)
![captura de tela de 2018-06-25 13-10-03](https://user-images.githubusercontent.com/35929939/41868003-567bb6e0-787a-11e8-9d23-cef4ff9c1b15.png)
![captura de tela de 2018-06-25 13-11-13](https://user-images.githubusercontent.com/35929939/41868004-5698f958-787a-11e8-8636-cd036d7af6c3.png)

**Comment by RaulDurand** [comment]
In this case an argument jointtag="my-joint-tag" is required when creating a BlockInset.  The tag argument will set the tag for line (rod) cells and jointtag for the joint cells. Thus, different tags can be used. Later, those tags can be used when setting material properties.

**Comment by RaulDurand** [comment]
The BlockInset structure is from the FemMesh library. Please run Pkg.update() if necessary.

**Comment by bgpantojar** [comment]
I got to resolve this problem with the jointtag recomendation. Thanks
