### ISSUE TITLE
Amaru: get_segment_data not defined

### ISSUE THREAD

**Issue by pedroflcUnB** [NumSoftware/Amaru#27]
I'm trying to use Amaru but this error is appearing: UndefVarError: get_segment_data not defined. Does anyone have any solution?

**Comment by RaulDurand** [comment]
Did you get the last updates? 
FemMesh is a dependency so you'll need to update it as well.
Could you provide a minimum working example? 
Do you get the error when loading the library? `using Amaru` ?
Did you install these libraries as developer? In that case you'll need to update them using git. e.g. `$ git pull`.

**Comment by pedroflcUnB** [comment]
I got the last updates. I was forgetting to update FemMesh using git pull. I did it only for Amaru. Now both it working correctly. Thanks professor.
