### ISSUE TITLE
Problem to define thermo materials

### ISSUE THREAD

**Issue by pedroflcUnB** [NumSoftware/Amaru#28]
_**Is the new updates modified the commands to define materials?**_

**_I'm using:_**

`materials = [
             "solids" => LinThermo(k=k, rho=rho, cv=cv)
            ]`

**_and it's showed this message:_**

`ERROR: LoadError: MethodError: no method matching ip_state_type(::LinThermo)
Closest candidates are:
  ip_state_type(::ElasticSolid) at C:\Users\lenovo\.julia\dev\Amaru\src\mech\mat\elastic-solid.jl:43

  ip_state_type(::DruckerPrager) at C:\Users\lenovo\.julia\dev\Amaru\src\mech\mat\dp-solid.jl:49 

  ip_state_type(::VonMises) at C:\Users\lenovo\.julia\dev\Amaru\src\mech\mat\vm-solid.jl:45
  ...`

**Comment by RaulDurand** [comment]
You'll need to define a function that returns the type of IpState together git your model, for instance:

`ip_state_type(mat::LinThermo) = LinThermoIpState`

**Comment by pedroflcUnB** [comment]
I fixed it.
Now another error appeared:

> ERROR: LoadError: **type Domain has no field stage**
> Stacktrace:
>  [1] getproperty(::Any, ::Symbol) at .\Base.jl:20
>  [2] #tm_solve!#639(::Float64, ::Float64, ::Int64, ::Int64, ::Bool, ::Float64, ::Bool, ::Bool, ::Int64, ::Symbol, ::typeof(tm_solve!), ::Domain, ::Array{Pair{Expr,NodeBC},1}) at C:\Users\lenovo\.julia\dev\Amaru\src\thermomech\thermomech-solver.jl:169
>  [3] (::getfield(Amaru, Symbol("#kw##tm_solve!")))(::NamedTuple{(:end_time, :tol, :nincs, :verbose),Tuple{Float64,Float64,Int64,Bool}}, ::typeof(tm_solve!), ::Domain, ::Array{Pair{Expr,NodeBC},1}) at .\none:0

**Comment by RaulDurand** [comment]
Seems to be working now.
