### ISSUE TITLE
Smoth in .msh format

### ISSUE THREAD

**Issue by bgpantojar** [NumSoftware/Amaru#29]
Dear Raul,

I was trying to use the smoth!() function in a .msh file and realized that is not working anymore with these type of files. I just was wondering if the last updates meant to do that or if it is a bug to be solved.

![Screenshot from 2020-08-11 14-21-04](https://user-images.githubusercontent.com/35929939/89896561-f0a7b700-dbdd-11ea-98bf-c226c2f1d7f0.png)

Best,
Bryan

**Comment by RaulDurand** [comment]
Yeah, thats true. There was a msh format we used long time ago but it was different from the Gmsh native format. Where did you get your file from?

**Comment by bgpantojar** [comment]
Originally it was a .stl file with a surface mesh. Afterward, it was used gmsh to generate the volume mesh as .msh. Anyways, I will save it as one of the formats compatible with Amaru.

**Comment by RaulDurand** [comment]
Gmsh exports to vtk format, which can be used in Amaru.

**Comment by bgpantojar** [comment]
I will do that. Thanks a lot.
